version: "3.11"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

    python:
        build: .
        container_name: python
        restart: always
        ports:
            - "8080:5000"
        volumes:
            - ./:/app
        depends_on:
            - postgres